<a href="https://colab.research.google.com/github/log-ghj/automatic-model-selection/blob/main/ridge_CV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
import pandas as pd
from statsmodels.tools.tools import add_constant
from sklearn.linear_model import Ridge
import scipy
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures

In [33]:
#Read the data
df = pd.read_csv('https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv').dropna()

#Convert number of rooms into per person values
df["total_rooms_pp"] = df["total_rooms"]/df["population"]
df["total_bedrooms_pp"] = df["total_bedrooms"]/df["population"]
#Average hosuehold size
df["household_size"] = df["population"]/df["households"]
#Drop some variables
df=df.drop(["total_rooms", "total_bedrooms", "households"], axis=1)

#Make the categorical variable into a set of dummies
xx = pd.get_dummies(df.ocean_proximity)
df = pd.concat([df, xx], axis=1, sort=False)
del df["ocean_proximity"]

In [35]:
#Cluster geolocations - determine the optimal number of clusters
from sklearn import preprocessing, cluster
X = df[["latitude","longitude"]]
max_k = 10
## iterations
distortions = [] 
for i in range(1, max_k+1):
    if len(X) >= i:
       model = cluster.KMeans(n_clusters=i, init='k-means++', max_iter=300, n_init=10, random_state=0)
       model.fit(X)
       distortions.append(model.inertia_)
## best k: the lowest derivative
k = [i*100 for i in np.diff(distortions,2)].index(min([i*100 for i 
     in np.diff(distortions,2)]))

In [36]:
#Cluster geolocations - create clusters
import scipy.cluster
k = 6
model = cluster.KMeans(n_clusters=k, init='k-means++')
X = df[["latitude","longitude"]]
# clustering
df_X = X.copy()
df_X["cluster"] = model.fit_predict(X)
# find real centroids
closest, distances = scipy.cluster.vq.vq(model.cluster_centers_, df_X.drop("cluster", axis=1).values)
df_X["centroids"] = 0
for i in closest:
    df_X["centroids"].iloc[i] = 1
# add clustering info to the original dataset
df[["cluster"]] = df_X[["cluster"]]

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


In [37]:
from sklearn.base import BaseEstimator 
from sklearn.base import RegressorMixin

In [38]:
class self_coded_ridge(BaseEstimator, RegressorMixin):
    def __init__(self, λ=1, **model_hyper_parameters):
        """
        """
        super().__init__()
        self.λ = λ
        self.X_train = None
        # fitted parameters, initialized to None
        self.params = None

    def set_params(self, **params):
        """
        """
        if not params:
            # Simple optimization to gain speed (inspect is slow)
            return self
        valid_params = self.get_params(deep=True)

        nested_params = defaultdict(dict)  # grouped by prefix
        for key, value in params.items():
            key, delim, sub_key = key.partition('__')
            if key not in valid_params:
                raise ValueError('Invalid parameter %s for estimator %s. '
                                 'Check the list of available parameters '
                                 'with `estimator.get_params().keys()`.' %
                                 (key, self))

            if delim:
                nested_params[key][sub_key] = value
            else:
                setattr(self, key, value)
                valid_params[key] = value

        for key, sub_params in nested_params.items():
            valid_params[key].set_params(**sub_params)

        return self

    def fit(self, X_train, y_train):
        """
        """
        X_train, y_train, λ = np.asarray(add_constant(X_train, prepend=True)), np.asarray(y_train), self.λ 
        self.X_train = X_train
        XX = X_train.T@X_train
        β = np.linalg.inv(XX+λ*np.eye(N=len(XX)))@X_train.T@y_train
        self.params = β
        return self.params

    def predict(self, X_test):
        β = self.params
        return X_test@β

    def get_params(self, deep = False):
        return {'λ':self.λ}

In [39]:
# Define a function that does CV on a grid to find optimal value of the hyperparameter
def ridge_self_coded(grid,X,y):
  coefs = []
  ics = []

  for a in grid:
    ridge = self_coded_ridge(a)
    ridge.fit(X, y)
    coefs.append(ridge.params)
    k=10 #k-fold CV
    scores = cross_val_score(ridge, X, y, cv=k, scoring='neg_mean_squared_error')
    RMSE = np.sqrt(sum(abs(scores))/k)
    ics.append(RMSE)
  opt = ics.index(min(ics))
  return coefs[opt], grid[opt], ics[opt]

In [40]:
# Create a similar function for the pre-existing sklearn ridge for comparison
def ridge_sklearn(lambdas, X, y):
  ridge = Ridge(fit_intercept=False, normalize=False) # do not use sklearn's normalization as it divides by L2 and not std.
  coefs = []
  ics = []

  for a in lambdas:
    ridge.set_params(alpha = a)
    ridge.fit(X, y)
    coefs.append(ridge.coef_)
    k=10 #k-fold CV
    scores = cross_val_score(ridge, X, y, cv=k, scoring='neg_mean_squared_error')
    RMSE = np.sqrt(sum(abs(scores))/k)
    ics.append(RMSE)
  opt = ics.index(min(ics))
  return coefs[opt], lambdas[opt], ics[opt]

In [41]:
# create grid of lambdas
# doing what is called naive implementation in the slides -> max value of grid chosen
# efficient way is through SVD -> left to do
grid = 10**np.linspace(4,-2,100)*0.5

# split l.h.s, and r.h.s.
X = df.drop(['median_house_value'], axis=1)
y = df.median_house_value

# normalize data
X = (X-X.mean())/X.std()
y = y-y.mean()

poly = PolynomialFeatures(2)
X = poly.fit_transform(X)

In [42]:
X.shape

(20433, 120)

In [80]:
result_self_coded = ridge_self_coded(grid, X, y)
result_self_coded

(array([ 1.16643471e+02, -2.25377765e+04, -1.39380622e+04,  1.01356498e+04,
         6.62991990e+03,  6.21045182e+04,  2.04297949e+04,  3.54280839e+04,
        -6.55345345e+03,  9.46657072e+03, -1.10463083e+04, -1.74364733e+00,
        -5.34894835e+02,  1.82375774e+03, -1.20271363e+04, -1.94956260e+03,
         8.19371655e+03, -6.40258893e+03,  2.32882051e+03, -8.56149870e+03,
         2.72676580e+03, -3.50921189e+02, -3.78683228e+02,  2.95254676e+03,
         1.32645617e+03,  5.65088844e+02, -7.11656959e+03,  4.28651781e+02,
         1.47850511e+03, -7.17523807e+03, -9.78585762e+03,  2.81378014e+03,
        -9.83186739e+03, -1.10620957e+03,  9.64596325e+02, -1.43944210e+03,
         4.13364518e+03, -5.69603895e+02,  1.34290042e+02, -7.34585726e+03,
         1.54924180e+03, -7.26968607e+03,  2.56416902e+03,  4.70814132e+03,
         2.92833263e+03,  2.08148122e+02,  1.14584138e+04, -2.43175023e+03,
        -1.81149901e+03, -1.15909864e+03, -7.11207120e+01,  4.58773760e+03,
        -3.4

In [82]:
result_sklearn = ridge_sklearn(grid, X, y)
result_sklearn

(array([ 1.16643471e+02, -2.25377765e+04, -1.39380622e+04,  1.01356498e+04,
         6.62991990e+03,  6.21045182e+04,  2.04297949e+04,  3.54280839e+04,
        -6.55345345e+03,  9.46657072e+03, -1.10463083e+04, -1.74364733e+00,
        -5.34894835e+02,  1.82375774e+03, -1.20271363e+04, -1.94956260e+03,
         8.19371655e+03, -6.40258893e+03,  2.32882051e+03, -8.56149870e+03,
         2.72676580e+03, -3.50921189e+02, -3.78683228e+02,  2.95254676e+03,
         1.32645617e+03,  5.65088844e+02, -7.11656959e+03,  4.28651781e+02,
         1.47850511e+03, -7.17523807e+03, -9.78585762e+03,  2.81378014e+03,
        -9.83186739e+03, -1.10620957e+03,  9.64596325e+02, -1.43944210e+03,
         4.13364518e+03, -5.69603895e+02,  1.34290042e+02, -7.34585726e+03,
         1.54924180e+03, -7.26968607e+03,  2.56416902e+03,  4.70814132e+03,
         2.92833263e+03,  2.08148122e+02,  1.14584138e+04, -2.43175023e+03,
        -1.81149901e+03, -1.15909864e+03, -7.11207120e+01,  4.58773760e+03,
        -3.4

In [83]:
# instead of the above arbitrarily defined grid, find a grid with the help of svd
# from ols to ridge D**-1 is multiplied by (D**2+λ)**(-1) D**2 (1)
# df of ols are 120 (with poly) -> find λ s.t. (1) = ~120/~0
import scipy
u,s,v = scipy.linalg.svd(X)

In [84]:
sum(s**2/(s**2))

120.0

In [85]:
x1 = 1e-30
x2 = 1_000_000_000

In [86]:
print(sum(s**2/(s**2+x1)),sum(s**2/(s**2+x2)))

119.99989752904895 0.29988341244594074


In [87]:
# define a new grid with above valuees
new_grid = np.linspace(x1,x2,100)

In [94]:
new_grid = np.append(new_grid,result_self_coded[1])

In [95]:
ridge_self_coded(new_grid, X, y)

(array([ 1.16643471e+02, -2.25377765e+04, -1.39380622e+04,  1.01356498e+04,
         6.62991990e+03,  6.21045182e+04,  2.04297949e+04,  3.54280839e+04,
        -6.55345345e+03,  9.46657072e+03, -1.10463083e+04, -1.74364733e+00,
        -5.34894835e+02,  1.82375774e+03, -1.20271363e+04, -1.94956260e+03,
         8.19371655e+03, -6.40258893e+03,  2.32882051e+03, -8.56149870e+03,
         2.72676580e+03, -3.50921189e+02, -3.78683228e+02,  2.95254676e+03,
         1.32645617e+03,  5.65088844e+02, -7.11656959e+03,  4.28651781e+02,
         1.47850511e+03, -7.17523807e+03, -9.78585762e+03,  2.81378014e+03,
        -9.83186739e+03, -1.10620957e+03,  9.64596325e+02, -1.43944210e+03,
         4.13364518e+03, -5.69603895e+02,  1.34290042e+02, -7.34585726e+03,
         1.54924180e+03, -7.26968607e+03,  2.56416902e+03,  4.70814132e+03,
         2.92833263e+03,  2.08148122e+02,  1.14584138e+04, -2.43175023e+03,
        -1.81149901e+03, -1.15909864e+03, -7.11207120e+01,  4.58773760e+03,
        -3.4

In [96]:
ridge_sklearn(new_grid, X, y)

(array([ 1.16643471e+02, -2.25377765e+04, -1.39380622e+04,  1.01356498e+04,
         6.62991990e+03,  6.21045182e+04,  2.04297949e+04,  3.54280839e+04,
        -6.55345345e+03,  9.46657072e+03, -1.10463083e+04, -1.74364733e+00,
        -5.34894835e+02,  1.82375774e+03, -1.20271363e+04, -1.94956260e+03,
         8.19371655e+03, -6.40258893e+03,  2.32882051e+03, -8.56149870e+03,
         2.72676580e+03, -3.50921189e+02, -3.78683228e+02,  2.95254676e+03,
         1.32645617e+03,  5.65088844e+02, -7.11656959e+03,  4.28651781e+02,
         1.47850511e+03, -7.17523807e+03, -9.78585762e+03,  2.81378014e+03,
        -9.83186739e+03, -1.10620957e+03,  9.64596325e+02, -1.43944210e+03,
         4.13364518e+03, -5.69603895e+02,  1.34290042e+02, -7.34585726e+03,
         1.54924180e+03, -7.26968607e+03,  2.56416902e+03,  4.70814132e+03,
         2.92833263e+03,  2.08148122e+02,  1.14584138e+04, -2.43175023e+03,
        -1.81149901e+03, -1.15909864e+03, -7.11207120e+01,  4.58773760e+03,
        -3.4